import type { ImportExportTemplate, ImportExportType } from "@/lib/import-export/types"

export const IMPORT_EXPORT_TEMPLATES: Record<ImportExportType, ImportExportTemplate> = {
  students: {
    type: "students",
    label: "SIS Student Import",
    filename: "students-import-template.csv",
    columns: [
      { key: "mdId", label: "MD ID", required: false, description: "Madonna student badge number — auto-assigned when omitted if email is present" },
      { key: "firstName", label: "First Name", required: false, description: "Given name (or use Student Name as Last, First)" },
      { key: "lastName", label: "Last Name", required: false },
      { key: "grade", label: "Grade", required: false, description: "Optional — overridden by email class year when present" },
      { key: "photoUrl", label: "Photo URL", required: false, description: "Optional URL; empty OK" },
      { key: "badgeStatus", label: "Badge Status", required: false, description: "active | pending | inactive (or yes/no); empty → active" },
      { key: "barcode", label: "Barcode", required: false, description: "Physical badge number if different from MD ID; defaults to MD ID" },
      {
        key: "password",
        label: "Password",
        required: false,
        description:
          "Temporary portal password (8+ characters). Sets mustChangePassword — student must change it on first /login/student. Leave blank to skip portal password",
      },
      { key: "studentName", label: "Student Name", required: false, description: "Directory form: Last, First" },
      { key: "email", label: "Student Email", required: false, description: "School email (…27@weirtonmadonna.org) — sets grade from class year; preferred student portal login" },
      { key: "balance", label: "Balance", required: false, description: "Optional — defaults to 0.00 if blank; $ and commas OK" },
      { key: "parent", label: "Parent Name", required: false, description: "Optional parent/guardian name" },
      { key: "parentEmail", label: "Parent Email", required: false },
      { key: "photo", label: "Photo", required: false, description: "Optional filename or path" },
      { key: "homeroom", label: "Homeroom", required: false },
      { key: "parentPhone", label: "Parent Phone", required: false },
      { key: "allergies", label: "Allergies", required: false, description: "Comma-separated list" },
      { key: "dietaryRestrictions", label: "Dietary Restrictions", required: false },
    ],
    sampleRow: {
      mdId: "MD0001",
      firstName: "First",
      lastName: "Last",
      grade: "10",
      photoUrl: "https://example.com/photos/MD0001.jpg",
      badgeStatus: "active",
      barcode: "MD0001",
      password: "Madonna26",
      email: "",
      balance: "0.00",
      parent: "Parent Name",
      parentEmail: "parent@example.com",
      photo: "",
      homeroom: "10A",
      parentPhone: "555-0100",
      allergies: "Peanut",
      dietaryRestrictions: "",
    },
  },
  studentPortal: {
    type: "studentPortal",
    label: "Student Portal Accounts",
    filename: "student-portal-accounts-template.csv",
    columns: [
      {
        key: "mdId",
        label: "MD ID",
        required: true,
        description: "Madonna student badge / external ID — must already exist on the roster",
      },
      {
        key: "email",
        label: "Email",
        required: false,
        description: "School email (…@weirtonmadonna.org). Optional if already on the roster",
      },
      {
        key: "password",
        label: "Password",
        required: false,
        description:
          "Temporary password (8+ characters). Students must change it on first login. Leave blank to use the default bulk temporary password",
      },
    ],
    sampleRow: {
      mdId: "MD12214",
      email: "",
      password: "Madonna26",
    },
  },
  parents: {
    type: "parents",
    label: "Parent Contacts",
    filename: "parent-contacts-import-template.csv",
    columns: [
      { key: "parentEmail", label: "Parent Email", required: true },
      { key: "parentName", label: "Parent Name", required: true },
      { key: "parentPhone", label: "Phone", required: false },
      { key: "mdId", label: "Student MD ID", required: true },
      { key: "relationship", label: "Relationship", required: false },
    ],
    sampleRow: {
      parentEmail: "parent@example.com",
      parentName: "Parent Name",
      parentPhone: "555-0100",
      mdId: "MD0001",
      relationship: "Mother",
    },
  },
  staff: {
    type: "staff",
    label: "Staff Account Import",
    filename: "staff-import-template.csv",
    columns: [
      { key: "firstName", label: "First Name", required: true },
      { key: "lastName", label: "Last Name", required: true },
      { key: "email", label: "Email", required: true },
      { key: "role", label: "Role", required: true, description: "admin, cashier, staff, or teacher" },
      { key: "department", label: "Department", required: false, description: "e.g. Math Department, Cafeteria" },
      { key: "username", label: "Username", required: false, description: "Defaults to email local part" },
      { key: "phone", label: "Phone", required: false },
      { key: "badgeId", label: "Badge ID", required: false, description: "Staff badge number when applicable" },
      { key: "password", label: "Password", required: false, description: "Temporary password — leave blank to use default bulk password; user must change on first login" },
    ],
    sampleRow: {
      firstName: "First",
      lastName: "Last",
      email: "staff@example.com",
      role: "teacher",
      department: "Science Department",
      username: "staff.user",
      phone: "555-0100",
      badgeId: "90001",
      password: "",
    },
  },
  families: {
    type: "families",
    label: "Family & User Import",
    filename: "family-user-import-template.csv",
    columns: [
      { key: "parentEmail", label: "Parent Email", required: true, description: "Creates parent login" },
      { key: "parentFirstName", label: "Parent First Name", required: true },
      { key: "parentLastName", label: "Parent Last Name", required: true },
      { key: "parentPhone", label: "Parent Phone", required: false },
      { key: "parentUsername", label: "Parent Username", required: false, description: "Defaults to email local part" },
      { key: "studentMdId", label: "Student MD ID", required: true, description: "Links to existing student or creates new" },
      { key: "studentFirstName", label: "Student First Name", required: false, description: "Required when creating new student" },
      { key: "studentLastName", label: "Student Last Name", required: false, description: "Required when creating new student" },
      { key: "grade", label: "Grade", required: false, description: "Required when creating new student" },
      { key: "balance", label: "Balance", required: false, description: "Required when creating new student" },
      { key: "relationship", label: "Relationship", required: false, description: "Mother, Father, or Guardian" },
      { key: "password", label: "Password", required: false, description: "Temporary password — leave blank to generate; user must change on first login" },
      { key: "sendWelcomeEmail", label: "Send Welcome Email", required: false, description: "yes or no" },
    ],
    sampleRow: {
      parentEmail: "parent@example.com",
      parentFirstName: "Parent",
      parentLastName: "Name",
      parentPhone: "555-0100",
      parentUsername: "parent.name",
      studentMdId: "MD0001",
      studentFirstName: "First",
      studentLastName: "Last",
      grade: "7",
      balance: "0.00",
      relationship: "Mother",
      password: "",
      sendWelcomeEmail: "yes",
    },
  },
  badges: {
    type: "badges",
    label: "Badge Enrollment",
    filename: "badge-enrollment-template.csv",
    columns: [
      { key: "mdId", label: "MD ID", required: true },
      { key: "firstName", label: "First Name", required: true },
      { key: "lastName", label: "Last Name", required: true },
      { key: "grade", label: "Grade", required: true },
      { key: "photoUrl", label: "Photo URL", required: false },
      { key: "badgeStatus", label: "Badge Status", required: false, description: "active | pending | inactive" },
      { key: "barcode", label: "Barcode", required: false, description: "Physical badge number if different from MD ID" },
    ],
    sampleRow: {
      mdId: "MD0001",
      firstName: "First",
      lastName: "Last",
      grade: "7",
      photoUrl: "https://example.com/photos/MD0001.jpg",
      badgeStatus: "active",
      barcode: "MD0001",
    },
  },
  menu: {
    type: "menu",
    label: "Menu Items",
    filename: "menu-items-import-template.csv",
    columns: [
      { key: "name", label: "Meal Name", required: true },
      { key: "category", label: "Category", required: true },
      { key: "price", label: "Price", required: true },
      { key: "description", label: "Description", required: false },
      { key: "allergens", label: "Allergens", required: false },
      { key: "photoUrl", label: "Photo URL", required: false },
    ],
    sampleRow: {
      name: "Grilled Chicken Bowl",
      category: "Entree",
      price: "4.50",
      description: "Grilled chicken with rice and vegetables",
      allergens: "Gluten",
      photoUrl: "",
    },
  },
  inventory: {
    type: "inventory",
    label: "Inventory Items",
    filename: "inventory-import-template.csv",
    columns: [
      { key: "name", label: "Item Name", required: true },
      { key: "category", label: "Category", required: true },
      { key: "qty", label: "Quantity", required: true },
      { key: "unit", label: "Unit", required: true },
      { key: "cost", label: "Unit Cost", required: true },
      { key: "barcode", label: "Barcode", required: false },
      { key: "expiration", label: "Expiration Date", required: false, description: "YYYY-MM-DD" },
      { key: "storageLocation", label: "Storage Location", required: false },
    ],
    sampleRow: {
      name: "Chicken Breast",
      category: "Protein",
      qty: "50",
      unit: "lb",
      cost: "3.25",
      barcode: "012345678901",
      expiration: "2026-08-15",
      storageLocation: "Walk-in Freezer",
    },
  },
  pricing: {
    type: "pricing",
    label: "Meal Pricing",
    filename: "pricing-import-template.csv",
    columns: [
      { key: "mealType", label: "Meal Type", required: true },
      { key: "price", label: "Price", required: true },
      { key: "subsidyEligible", label: "Subsidy Eligible", required: false },
      { key: "effectiveDate", label: "Effective Date", required: false },
    ],
    sampleRow: {
      mealType: "Full Lunch",
      price: "7.00",
      subsidyEligible: "yes",
      effectiveDate: "2026-08-01",
    },
  },
  vendors: {
    type: "vendors",
    label: "Vendors",
    filename: "vendors-import-template.csv",
    columns: [
      { key: "name", label: "Vendor Name", required: true },
      { key: "contactName", label: "Contact Name", required: false },
      { key: "email", label: "Email", required: false },
      { key: "phone", label: "Phone", required: false },
      { key: "category", label: "Category", required: false },
    ],
    sampleRow: {
      name: "Example Vendor",
      contactName: "Contact Name",
      email: "orders@example.com",
      phone: "555-1000",
      category: "Food Service",
    },
  },
}

export function getTemplate(type: ImportExportType): ImportExportTemplate {
  return IMPORT_EXPORT_TEMPLATES[type]
}
