import type { ImportExportTemplate, ImportExportType } from "@/lib/import-export/types"

export const IMPORT_EXPORT_TEMPLATES: Record<ImportExportType, ImportExportTemplate> = {
  students: {
    type: "students",
    label: "SIS Student Import",
    filename: "sis-student-import-template.csv",
    columns: [
      { key: "mdId", label: "MD ID", required: true, description: "Madonna student badge number" },
      { key: "firstName", label: "First Name", required: true },
      { key: "lastName", label: "Last Name", required: true },
      { key: "grade", label: "Grade", required: true },
      { key: "homeroom", label: "Homeroom", required: false },
      { key: "balance", label: "Balance", required: true },
      { key: "photoUrl", label: "Photo URL", required: false, description: "URL or filename for student photo" },
      { key: "parentEmail", label: "Parent Email", required: false },
      { key: "parentPhone", label: "Parent Phone", required: false },
      { key: "allergies", label: "Allergies", required: false, description: "Comma-separated list" },
      { key: "dietaryRestrictions", label: "Dietary Restrictions", required: false },
    ],
    sampleRow: {
      mdId: "10457",
      firstName: "James",
      lastName: "Anderson",
      grade: "10",
      homeroom: "10B",
      balance: "0.00",
      photoUrl: "https://example.com/photos/10457.jpg",
      parentEmail: "parent@email.com",
      parentPhone: "555-0100",
      allergies: "Peanut",
      dietaryRestrictions: "",
    },
  },
  parents: {
    type: "parents",
    label: "Parent Contacts",
    filename: "parent-contacts-import-template.csv",
    columns: [
      { key: "parentEmail", label: "Parent Email", required: true },
      { key: "parentName", label: "Parent Name", required: true },
      { key: "parentPhone", label: "Phone", required: false },
      { key: "mdId", label: "Student MD ID", required: true },
      { key: "relationship", label: "Relationship", required: false },
    ],
    sampleRow: {
      parentEmail: "sarah.anderson@email.com",
      parentName: "Sarah Anderson",
      parentPhone: "555-0201",
      mdId: "10457",
      relationship: "Mother",
    },
  },
  badges: {
    type: "badges",
    label: "Badge Enrollment",
    filename: "badge-enrollment-template.csv",
    columns: [
      { key: "mdId", label: "MD ID", required: true },
      { key: "firstName", label: "First Name", required: true },
      { key: "lastName", label: "Last Name", required: true },
      { key: "grade", label: "Grade", required: true },
      { key: "photoUrl", label: "Photo URL", required: false },
      { key: "badgeStatus", label: "Badge Status", required: false, description: "active | pending | inactive" },
    ],
    sampleRow: {
      mdId: "10457",
      firstName: "James",
      lastName: "Anderson",
      grade: "10",
      photoUrl: "https://example.com/photos/10457.jpg",
      badgeStatus: "active",
    },
  },
  menu: {
    type: "menu",
    label: "Menu Items",
    filename: "menu-items-import-template.csv",
    columns: [
      { key: "name", label: "Meal Name", required: true },
      { key: "category", label: "Category", required: true },
      { key: "price", label: "Price", required: true },
      { key: "description", label: "Description", required: false },
      { key: "allergens", label: "Allergens", required: false },
      { key: "photoUrl", label: "Photo URL", required: false },
    ],
    sampleRow: {
      name: "Grilled Chicken Bowl",
      category: "Entree",
      price: "4.50",
      description: "Grilled chicken with rice and vegetables",
      allergens: "Gluten",
      photoUrl: "",
    },
  },
  inventory: {
    type: "inventory",
    label: "Inventory Items",
    filename: "inventory-import-template.csv",
    columns: [
      { key: "name", label: "Item Name", required: true },
      { key: "category", label: "Category", required: true },
      { key: "qty", label: "Quantity", required: true },
      { key: "unit", label: "Unit", required: true },
      { key: "cost", label: "Unit Cost", required: true },
      { key: "barcode", label: "Barcode", required: false },
      { key: "expiration", label: "Expiration Date", required: false, description: "YYYY-MM-DD" },
      { key: "storageLocation", label: "Storage Location", required: false },
    ],
    sampleRow: {
      name: "Chicken Breast",
      category: "Protein",
      qty: "50",
      unit: "lb",
      cost: "3.25",
      barcode: "012345678901",
      expiration: "2026-08-15",
      storageLocation: "Walk-in Freezer",
    },
  },
  pricing: {
    type: "pricing",
    label: "Meal Pricing",
    filename: "pricing-import-template.csv",
    columns: [
      { key: "mealType", label: "Meal Type", required: true },
      { key: "price", label: "Price", required: true },
      { key: "subsidyEligible", label: "Subsidy Eligible", required: false },
      { key: "effectiveDate", label: "Effective Date", required: false },
    ],
    sampleRow: {
      mealType: "Full Lunch",
      price: "4.50",
      subsidyEligible: "yes",
      effectiveDate: "2026-08-01",
    },
  },
  vendors: {
    type: "vendors",
    label: "Vendors",
    filename: "vendors-import-template.csv",
    columns: [
      { key: "name", label: "Vendor Name", required: true },
      { key: "contactName", label: "Contact Name", required: false },
      { key: "email", label: "Email", required: false },
      { key: "phone", label: "Phone", required: false },
      { key: "category", label: "Category", required: false },
    ],
    sampleRow: {
      name: "Sysco Foods",
      contactName: "John Smith",
      email: "orders@sysco.com",
      phone: "555-1000",
      category: "Food Service",
    },
  },
}

export function getTemplate(type: ImportExportType): ImportExportTemplate {
  return IMPORT_EXPORT_TEMPLATES[type]
}
