import type {
  InventoryMovement,
  OpsInventoryItem,
  ProductionOrder,
  ReceiptScan,
  ReceivingRecord,
  StorageLocation,
} from "@/lib/operations/types"

export const DEMO_STORAGE_LOCATIONS: StorageLocation[] = [
  { id: "loc-dry-1", name: "Dry Storage A", zone: "dry", capacity: 200, schoolId: "demo" },
  { id: "loc-cold-1", name: "Walk-in Cooler", zone: "cold", capacity: 80, schoolId: "demo" },
  { id: "loc-freezer-1", name: "Main Freezer", zone: "freezer", capacity: 60, schoolId: "demo" },
  { id: "loc-prep-1", name: "Prep Line", zone: "prep", capacity: 40, schoolId: "demo" },
]

export const DEMO_OPS_INVENTORY: OpsInventoryItem[] = [
  {
    id: "inv-1",
    name: "Chocolate Milk",
    qty: 24,
    unit: "cartons",
    cost: 0.65,
    expiration: "2026-05-18",
    category: "Dairy",
    lowStockThreshold: 10,
    barcode: "041000000001",
    storageLocationId: "loc-cold-1",
    schoolId: "demo",
  },
  {
    id: "inv-2",
    name: "Chicken Patties",
    qty: 8,
    unit: "cases",
    cost: 42.5,
    expiration: "2026-06-10",
    category: "Frozen",
    lowStockThreshold: 12,
    barcode: "041000000002",
    storageLocationId: "loc-freezer-1",
    schoolId: "demo",
  },
  {
    id: "inv-3",
    name: "Apple Slices",
    qty: 42,
    unit: "bags",
    cost: 3.25,
    expiration: "2026-05-14",
    category: "Produce",
    lowStockThreshold: 15,
    storageLocationId: "loc-cold-1",
    schoolId: "demo",
  },
  {
    id: "inv-4",
    name: "French Fries",
    qty: 5,
    unit: "cases",
    cost: 28,
    expiration: "2026-07-01",
    category: "Frozen",
    lowStockThreshold: 10,
    storageLocationId: "loc-freezer-1",
    schoolId: "demo",
  },
  {
    id: "inv-5",
    name: "Hamburger Buns",
    qty: 60,
    unit: "packs",
    cost: 2.15,
    expiration: "2026-05-13",
    category: "Bakery",
    lowStockThreshold: 20,
    storageLocationId: "loc-dry-1",
    schoolId: "demo",
  },
  {
    id: "inv-6",
    name: "Whole Wheat Bread",
    qty: 18,
    unit: "loaves",
    cost: 1.85,
    expiration: "2026-05-20",
    category: "Bakery",
    lowStockThreshold: 15,
    storageLocationId: "loc-dry-1",
    schoolId: "demo",
  },
  {
    id: "inv-7",
    name: "Orange Juice",
    qty: 3,
    unit: "gallons",
    cost: 4.5,
    expiration: "2026-05-12",
    category: "Beverages",
    lowStockThreshold: 5,
    barcode: "041000000007",
    storageLocationId: "loc-cold-1",
    schoolId: "demo",
  },
]

export const DEMO_MOVEMENTS: InventoryMovement[] = [
  {
    id: "mov-1",
    type: "receive",
    quantity: 24,
    note: "Sysco delivery",
    inventoryItemId: "inv-1",
    storageLocationId: "loc-cold-1",
    receivingRecordId: "rcv-2",
    schoolId: "demo",
    createdAt: "2026-06-12T09:20:00.000Z",
    createdBy: "Kitchen Staff",
  },
  {
    id: "mov-2",
    type: "production",
    quantity: -12,
    note: "Lunch service",
    inventoryItemId: "inv-2",
    schoolId: "demo",
    createdAt: "2026-06-13T12:30:00.000Z",
    createdBy: "Production",
  },
  {
    id: "mov-3",
    type: "waste",
    quantity: -2,
    note: "Expired produce",
    inventoryItemId: "inv-3",
    schoolId: "demo",
    createdAt: "2026-06-13T08:00:00.000Z",
    createdBy: "Kitchen Staff",
  },
]

export const DEMO_RECEIVING: ReceivingRecord[] = [
  {
    id: "rcv-1",
    vendorName: "Sysco Foods",
    invoiceNumber: "INV-88421",
    status: "pending_approval",
    lines: [
      { inventoryItemId: "inv-2", name: "Chicken Breast", quantity: 40, unit: "lb", unitCost: 2.85 },
      { name: "Whole Wheat Buns", quantity: 120, unit: "ea", unitCost: 0.35 },
    ],
    receivedAt: "2026-06-13T14:30:00.000Z",
    schoolId: "demo",
    createdAt: "2026-06-13T14:30:00.000Z",
    updatedAt: "2026-06-13T14:30:00.000Z",
  },
  {
    id: "rcv-2",
    vendorName: "Local Produce Co.",
    status: "approved",
    lines: [
      { inventoryItemId: "inv-3", name: "Romaine Lettuce", quantity: 24, unit: "head" },
      { name: "Cherry Tomatoes", quantity: 10, unit: "lb" },
    ],
    receivedAt: "2026-06-12T09:15:00.000Z",
    approvedAt: "2026-06-12T10:00:00.000Z",
    approvedBy: "Nutrition Office",
    schoolId: "demo",
    createdAt: "2026-06-12T09:15:00.000Z",
    updatedAt: "2026-06-12T10:00:00.000Z",
  },
  {
    id: "rcv-3",
    vendorName: "Dairy Direct",
    status: "draft",
    lines: [{ inventoryItemId: "inv-1", name: "Chocolate Milk", quantity: 48, unit: "cartons" }],
    schoolId: "demo",
    createdAt: "2026-06-14T08:00:00.000Z",
    updatedAt: "2026-06-14T08:00:00.000Z",
  },
]

export const DEMO_RECEIPT_SCANS: ReceiptScan[] = [
  {
    id: "rcp-1",
    fileName: "sysco-june-13.pdf",
    vendorGuess: "Sysco Foods",
    ocrText: "SYSCO FOODS\nInvoice INV-88421\nChicken Breast 40 lb\nTotal: $312.00",
    status: "matched",
    matchedReceivingId: "rcv-1",
    schoolId: "demo",
    createdAt: "2026-06-13T15:00:00.000Z",
  },
  {
    id: "rcp-2",
    fileName: "unknown-vendor.jpg",
    status: "unmatched",
    ocrText: "Receipt unreadable — manual review required",
    schoolId: "demo",
    createdAt: "2026-06-13T11:20:00.000Z",
  },
]

export const DEMO_PRODUCTION_ORDERS: ProductionOrder[] = [
  {
    id: "prod-1",
    title: "Tuesday Hot Lunch — Chicken Wraps",
    status: "in_progress",
    scheduledFor: "2026-06-14T11:00:00.000Z",
    portionsPlanned: 185,
    portionsMade: 92,
    mealTemplateId: "mt-1",
    notes: "185 student + 12 staff reservations",
    schoolId: "demo",
    createdAt: "2026-06-14T06:00:00.000Z",
    updatedAt: "2026-06-14T11:30:00.000Z",
  },
  {
    id: "prod-2",
    title: "Wednesday Salad Bar",
    status: "planned",
    scheduledFor: "2026-06-15T11:00:00.000Z",
    portionsPlanned: 160,
    portionsMade: 0,
    schoolId: "demo",
    createdAt: "2026-06-14T06:00:00.000Z",
    updatedAt: "2026-06-14T06:00:00.000Z",
  },
]

export function createInitialDemoStore() {
  return {
    storageLocations: structuredClone(DEMO_STORAGE_LOCATIONS),
    inventory: structuredClone(DEMO_OPS_INVENTORY),
    movements: structuredClone(DEMO_MOVEMENTS),
    receiving: structuredClone(DEMO_RECEIVING),
    receipts: structuredClone(DEMO_RECEIPT_SCANS),
    production: structuredClone(DEMO_PRODUCTION_ORDERS),
  }
}

export type DemoOperationsStore = ReturnType<typeof createInitialDemoStore>
